# Generated by Django 4.0 on 2022-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='acntspayslip_esitype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='acntspayslip_pftype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='acntspayslip_esi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='acntspayslip_pf',
            field=models.IntegerField(),
        ),
    ]
