# Generated by Django 4.0 on 2022-04-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0002_acntspayslip_acntspayslip_esitype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reported_issue',
            name='reported_issue_status',
        ),
    ]
